# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\window_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.disconnect_port_button = QtWidgets.QPushButton(self.groupBox_3)
        self.disconnect_port_button.setObjectName("disconnect_port_button")
        self.gridLayout_10.addWidget(self.disconnect_port_button, 2, 3, 1, 1)
        self.detect_port_button = QtWidgets.QPushButton(self.groupBox_3)
        self.detect_port_button.setObjectName("detect_port_button")
        self.gridLayout_10.addWidget(self.detect_port_button, 2, 2, 1, 1)
        self.connect_port_button = QtWidgets.QPushButton(self.groupBox_3)
        self.connect_port_button.setObjectName("connect_port_button")
        self.gridLayout_10.addWidget(self.connect_port_button, 2, 1, 1, 1)
        self.port_show_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.port_show_combobox.setObjectName("port_show_combobox")
        self.gridLayout_10.addWidget(self.port_show_combobox, 1, 1, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.frame_5 = QtWidgets.QFrame(self.frame_14)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 0, 0, 1, 1)
        self.CB_manual = QtWidgets.QCheckBox(self.frame_5)
        self.CB_manual.setText("")
        self.CB_manual.setObjectName("CB_manual")
        self.gridLayout_13.addWidget(self.CB_manual, 0, 1, 1, 1)
        self.gridLayout_30.addWidget(self.frame_5, 1, 2, 1, 1)
        self.PB_write_c = QtWidgets.QPushButton(self.frame_14)
        self.PB_write_c.setObjectName("PB_write_c")
        self.gridLayout_30.addWidget(self.PB_write_c, 1, 1, 1, 1)
        self.LE_command = QtWidgets.QLineEdit(self.frame_14)
        self.LE_command.setObjectName("LE_command")
        self.gridLayout_30.addWidget(self.LE_command, 0, 1, 1, 2)
        self.gridLayout_4.addWidget(self.frame_14, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_19.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 0, 5, 1, 1)
        self.LE_E3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E3.setObjectName("LE_E3")
        self.gridLayout.addWidget(self.LE_E3, 1, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_20.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 1, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_18.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 0, 2, 1, 1)
        self.LE_E2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E2.setObjectName("LE_E2")
        self.gridLayout.addWidget(self.LE_E2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.LE_E5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E5.setObjectName("LE_E5")
        self.gridLayout.addWidget(self.LE_E5, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.LE_E4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E4.setObjectName("LE_E4")
        self.gridLayout.addWidget(self.LE_E4, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 3, 1, 1)
        self.LE_E1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E1.setObjectName("LE_E1")
        self.gridLayout.addWidget(self.LE_E1, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.LE_E0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E0.setObjectName("LE_E0")
        self.gridLayout.addWidget(self.LE_E0, 0, 1, 1, 1)
        self.LE_E6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E6.setObjectName("LE_E6")
        self.gridLayout.addWidget(self.LE_E6, 3, 1, 1, 2)
        self.LE_E7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E7.setObjectName("LE_E7")
        self.gridLayout.addWidget(self.LE_E7, 4, 4, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_23.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 2, 5, 1, 1)
        self.LE_E9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E9.setObjectName("LE_E9")
        self.gridLayout.addWidget(self.LE_E9, 4, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_24.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 4, 2, 1, 1)
        self.LE_E8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_E8.setObjectName("LE_E8")
        self.gridLayout.addWidget(self.LE_E8, 3, 4, 1, 2)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_25.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 4, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.LE_current_command = QtWidgets.QLineEdit(self.frame_15)
        self.LE_current_command.setObjectName("LE_current_command")
        self.gridLayout_31.addWidget(self.LE_current_command, 0, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_15)
        self.label_43.setObjectName("label_43")
        self.gridLayout_31.addWidget(self.label_43, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_15, 5, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 9, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 3, 1, 1, 7)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 9, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 0, 6, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_3.addWidget(self.pushButton_15, 2, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 0, 11, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 10, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 12, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 2, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 9, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 2)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 0, 12, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 3, 10, 1, 3)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 0, 7, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 2, 2, 1, 4)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 9, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 2, 10, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 2, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 2, 1, 5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 10, 1, 2)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 1, 7, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 1, 12, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 6, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 0, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 463, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuParameters = QtWidgets.QMenu(self.menuBar)
        self.menuParameters.setObjectName("menuParameters")
        self.menuseq = QtWidgets.QMenu(self.menuBar)
        self.menuseq.setObjectName("menuseq")
        self.menutest = QtWidgets.QMenu(self.menuBar)
        self.menutest.setObjectName("menutest")
        self.menucommunication = QtWidgets.QMenu(self.menuBar)
        self.menucommunication.setObjectName("menucommunication")
        MainWindow.setMenuBar(self.menuBar)
        self.actionload = QtWidgets.QAction(MainWindow)
        self.actionload.setObjectName("actionload")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionload_2 = QtWidgets.QAction(MainWindow)
        self.actionload_2.setObjectName("actionload_2")
        self.actionstartDesi = QtWidgets.QAction(MainWindow)
        self.actionstartDesi.setObjectName("actionstartDesi")
        self.actionadd_LESA_point = QtWidgets.QAction(MainWindow)
        self.actionadd_LESA_point.setObjectName("actionadd_LESA_point")
        self.actionshow_LESA_point = QtWidgets.QAction(MainWindow)
        self.actionshow_LESA_point.setObjectName("actionshow_LESA_point")
        self.actionmove_to_point = QtWidgets.QAction(MainWindow)
        self.actionmove_to_point.setObjectName("actionmove_to_point")
        self.actionpop_LESA_point = QtWidgets.QAction(MainWindow)
        self.actionpop_LESA_point.setObjectName("actionpop_LESA_point")
        self.actionload_command_json = QtWidgets.QAction(MainWindow)
        self.actionload_command_json.setObjectName("actionload_command_json")
        self.actionload_command_text = QtWidgets.QAction(MainWindow)
        self.actionload_command_text.setObjectName("actionload_command_text")
        self.actionsend_parameters = QtWidgets.QAction(MainWindow)
        self.actionsend_parameters.setObjectName("actionsend_parameters")
        self.actionreport_pipe_size = QtWidgets.QAction(MainWindow)
        self.actionreport_pipe_size.setObjectName("actionreport_pipe_size")
        self.actionclear_send_pipe = QtWidgets.QAction(MainWindow)
        self.actionclear_send_pipe.setObjectName("actionclear_send_pipe")
        self.actionset_tastid_to_zero = QtWidgets.QAction(MainWindow)
        self.actionset_tastid_to_zero.setObjectName("actionset_tastid_to_zero")
        self.actionset_taskID = QtWidgets.QAction(MainWindow)
        self.actionset_taskID.setObjectName("actionset_taskID")
        self.actionreport_taskID = QtWidgets.QAction(MainWindow)
        self.actionreport_taskID.setObjectName("actionreport_taskID")
        self.actionauto_stanby = QtWidgets.QAction(MainWindow)
        self.actionauto_stanby.setCheckable(True)
        self.actionauto_stanby.setChecked(True)
        self.actionauto_stanby.setObjectName("actionauto_stanby")
        self.actionend_with_E99 = QtWidgets.QAction(MainWindow)
        self.actionend_with_E99.setCheckable(True)
        self.actionend_with_E99.setChecked(True)
        self.actionend_with_E99.setObjectName("actionend_with_E99")
        self.menuParameters.addAction(self.actionload)
        self.menuParameters.addAction(self.actionsave)
        self.menuParameters.addSeparator()
        self.menuParameters.addAction(self.actionauto_stanby)
        self.menuParameters.addAction(self.actionend_with_E99)
        self.menuseq.addAction(self.actionload_2)
        self.menuseq.addSeparator()
        self.menuseq.addAction(self.actionset_tastid_to_zero)
        self.menuseq.addAction(self.actionset_taskID)
        self.menuseq.addAction(self.actionreport_taskID)
        self.menutest.addAction(self.actionstartDesi)
        self.menutest.addAction(self.actionadd_LESA_point)
        self.menutest.addAction(self.actionpop_LESA_point)
        self.menutest.addAction(self.actionshow_LESA_point)
        self.menutest.addAction(self.actionmove_to_point)
        self.menutest.addSeparator()
        self.menutest.addAction(self.actionload_command_text)
        self.menucommunication.addAction(self.actionsend_parameters)
        self.menucommunication.addSeparator()
        self.menucommunication.addAction(self.actionreport_pipe_size)
        self.menucommunication.addSeparator()
        self.menucommunication.addAction(self.actionclear_send_pipe)
        self.menuBar.addAction(self.menuParameters.menuAction())
        self.menuBar.addAction(self.menuseq.menuAction())
        self.menuBar.addAction(self.menutest.menuAction())
        self.menuBar.addAction(self.menucommunication.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DEMO"))
        self.groupBox_3.setTitle(_translate("MainWindow", "serial"))
        self.disconnect_port_button.setText(_translate("MainWindow", "disconnect"))
        self.detect_port_button.setText(_translate("MainWindow", "detect"))
        self.connect_port_button.setText(_translate("MainWindow", "connect"))
        self.label_20.setText(_translate("MainWindow", "Manual:"))
        self.PB_write_c.setText(_translate("MainWindow", "write_c(F)"))
        self.LE_command.setText(_translate("MainWindow", "D1 X0 Y0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "MSI"))
        self.label_18.setText(_translate("MainWindow", "wait_T(s)"))
        self.pushButton_19.setText(_translate("MainWindow", "*"))
        self.LE_E3.setText(_translate("MainWindow", "2"))
        self.pushButton_20.setText(_translate("MainWindow", "*"))
        self.pushButton_21.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "front_x"))
        self.pushButton_22.setText(_translate("MainWindow", "*"))
        self.pushButton_18.setText(_translate("MainWindow", "*"))
        self.LE_E2.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "x_s"))
        self.label_6.setText(_translate("MainWindow", "y_e"))
        self.LE_E5.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "post_x"))
        self.label_4.setText(_translate("MainWindow", "x_e"))
        self.LE_E4.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "S_fr:"))
        self.LE_E1.setText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "MSI_fr:"))
        self.label_7.setText(_translate("MainWindow", "y_interval"))
        self.label_5.setText(_translate("MainWindow", "y_s"))
        self.LE_E0.setText(_translate("MainWindow", "0"))
        self.LE_E6.setText(_translate("MainWindow", "0.1"))
        self.LE_E7.setText(_translate("MainWindow", "200"))
        self.pushButton_23.setText(_translate("MainWindow", "*"))
        self.LE_E9.setText(_translate("MainWindow", "20"))
        self.pushButton_24.setText(_translate("MainWindow", "*"))
        self.LE_E8.setText(_translate("MainWindow", "5"))
        self.pushButton_25.setText(_translate("MainWindow", "*"))
        self.label_43.setText(_translate("MainWindow", "current command:"))
        self.groupBox.setTitle(_translate("MainWindow", "LESA"))
        self.label_16.setText(_translate("MainWindow", "ion_t(s)"))
        self.lineEdit_8.setText(_translate("MainWindow", "2000"))
        self.label_10.setText(_translate("MainWindow", "i_hight:"))
        self.pushButton_12.setText(_translate("MainWindow", "↓"))
        self.pushButton_15.setText(_translate("MainWindow", "!"))
        self.label_15.setText(_translate("MainWindow", "ext_t(ms)"))
        self.pushButton_14.setText(_translate("MainWindow", "↓"))
        self.lineEdit_3.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "*"))
        self.pushButton_10.setText(_translate("MainWindow", "*"))
        self.label_11.setText(_translate("MainWindow", "s_pos"))
        self.label_12.setText(_translate("MainWindow", "i_pos"))
        self.label_13.setText(_translate("MainWindow", "suck_t(ms)"))
        self.pushButton_13.setText(_translate("MainWindow", "↑"))
        self.lineEdit_9.setText(_translate("MainWindow", "240"))
        self.pushButton_11.setText(_translate("MainWindow", "↑"))
        self.lineEdit_6.setText(_translate("MainWindow", "100"))
        self.label_14.setText(_translate("MainWindow", "pump_t(ms)"))
        self.lineEdit_7.setText(_translate("MainWindow", "50"))
        self.lineEdit_2.setText(_translate("MainWindow", "5"))
        self.label_9.setText(_translate("MainWindow", "s_hight:"))
        self.lineEdit_4.setText(_translate("MainWindow", "2500"))
        self.lineEdit_5.setText(_translate("MainWindow", "3500"))
        self.pushButton_16.setText(_translate("MainWindow", "*"))
        self.pushButton_17.setText(_translate("MainWindow", "*"))
        self.pushButton.setText(_translate("MainWindow", "RUN_MSI"))
        self.pushButton_6.setText(_translate("MainWindow", "show_seq"))
        self.pushButton_5.setText(_translate("MainWindow", "load_seq"))
        self.pushButton_7.setText(_translate("MainWindow", "report_prog"))
        self.pushButton_4.setText(_translate("MainWindow", "STOP_MSI"))
        self.pushButton_3.setText(_translate("MainWindow", "STOP_LESA"))
        self.pushButton_2.setText(_translate("MainWindow", "RUN_LESA"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Host"))
        self.pushButton_8.setText(_translate("MainWindow", "ping_url"))
        self.label_19.setText(_translate("MainWindow", ":"))
        self.lineEdit_10.setText(_translate("MainWindow", "192.168.3.217:8750/"))
        self.checkBox.setText(_translate("MainWindow", "Remote"))
        self.menuParameters.setTitle(_translate("MainWindow", "Parameters"))
        self.menuseq.setTitle(_translate("MainWindow", "seq"))
        self.menutest.setTitle(_translate("MainWindow", "test"))
        self.menucommunication.setTitle(_translate("MainWindow", "communication"))
        self.actionload.setText(_translate("MainWindow", "load"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionload_2.setText(_translate("MainWindow", "load"))
        self.actionstartDesi.setText(_translate("MainWindow", "startDesi"))
        self.actionadd_LESA_point.setText(_translate("MainWindow", "add_LESA_point"))
        self.actionshow_LESA_point.setText(_translate("MainWindow", "show_LESA_point"))
        self.actionmove_to_point.setText(_translate("MainWindow", "move_to_point"))
        self.actionpop_LESA_point.setText(_translate("MainWindow", "pop_LESA_point"))
        self.actionload_command_json.setText(_translate("MainWindow", "load_command_json"))
        self.actionload_command_text.setText(_translate("MainWindow", "load_command_text"))
        self.actionsend_parameters.setText(_translate("MainWindow", "send_parameters"))
        self.actionreport_pipe_size.setText(_translate("MainWindow", "report_pipe_size"))
        self.actionclear_send_pipe.setText(_translate("MainWindow", "clear_send_pipe"))
        self.actionset_tastid_to_zero.setText(_translate("MainWindow", "set_taskID_to_zero"))
        self.actionset_taskID.setText(_translate("MainWindow", "set_taskID"))
        self.actionreport_taskID.setText(_translate("MainWindow", "report_taskID"))
        self.actionauto_stanby.setText(_translate("MainWindow", "auto_stanby"))
        self.actionend_with_E99.setText(_translate("MainWindow", "end_with_$E99"))

